### ISSUE TITLE
I acknowledge your efforts - this app looks amazing.

### ISSUE THREAD

**Issue by johndpope** [laurasirco/The-Algorithmic-Composer-MAC#1]
I would love to play with your app but it's not so simple to compile.
I did find an included binary in an earlier commit - which loaded a screen. 

There are a lot of missing classes - dependenceis / an older version of of_v0.8.0_osx_release
and then the subsequent addons. 
the older v0.8.0 library has a problem on 10.11 with SSL. 
 ofxui is DEPRECATED - and they suggest to use 0.8.4 - I guess you have moved on from this project - but I acknowledge your efforts. 

Do you have a dmg / binary file you can upload into this project so I can play with it?
I've been building something for making music with the piano > http://komposer.io

I wonder whether it would be an idea to throw out the ui /  app  code / open frameworks / and provide a purely the algorithm components - then a separate project could glue them together. 

Thanks
JP

**Comment by johndpope** [comment]
I totally missed the website URL. - http://thealgorithmiccomposer.tumblr.com/
You mentioned something about uploading codeblocks project? Would that help getting app to build? Or is it another project?

**Comment by laurasirco** [comment]
@johndpope
In the website URL you can find a link to the compiled app, it's been more than a year I havent been playing with this app (it was a final degree project), so I dunno if is there are problems with OSX 10.11. There is too a Windows compiled version!

The algorithmic composition files are already separated of the UI code, (maybe there are logs or something related to OpenFrameworks, but it's easily separable from it, I remember coding with this separation in mind all the time). Maybe I can make a new project with all the composition methods, like a library or something like that, without dependencies to OpenFrameworks. 

About the Codeblocks project, I forgot to put the project in public, here it is: https://github.com/laurasirco/The-Algorithmic-Composer-Windows

Your app Komposer looks amazing! :)

**Comment by johndpope** [comment]
hey @laurasirco - I'm closing out old gitbub tickets. 
thanks for your efforts here. Are you doing anything with tensorflow these days?
I had a dream to rig up my komposer app with it. made some progress with grpc + swift the other week https://github.com/nubbel/swift-tensorflow/
